name: Cypress CI E2E on Chrome
on: 
  # Manual button click from the GitHub UI
  workflow_dispatch:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # let's make sure our tests pass on Chrome browser
    name: E2E on Chrome
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v4.2.0
        with:
          browser: chrome
          start: npm start
          wait-on: 'http://localhost:3000'
          # record: true
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: NPM Install
        run: npm ci

      - name: Install Start Server and Test
        run: npm install start-server-and-test --no-save

      - name: Run Application and Cypress E2E Tests
        run: npx start-server-and-test start http://localhost:3000 test

      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Cypress screenshots
          path: cypress/screenshots

      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Cypress videos
          path: cypress/videos